config/routes.rb
Rails.application.routes.draw do
  

  resources :depreciation_details
  resources :depreciations
  resources :revaluation_coefficients
   resources :man_power_details
   resources :cost_oper_machines
   resources :type_machines
   root to: "home#index"
   #match 'history_sales' => 'type_of_crops/history_sales', :via => :post


   resources :history_sales,:type_of_crops, :program_productions, :people , :farming_plots, :manu_indi_expense_dets, :manu_indi_expenses, :stru_expense_dets
   resources :structure_expenses, :mark_spending_dets, :mark_spendings, :supply_details, :supplies, :chart_of_accounts, :cost_oper_machine_conts
   resources :cost_oper_machine_cont_details, :type_of_services, :fuels,:cost_oper_machine_details,:cost_oper_machines, :implements
   resources :machines, :models, :brands, :type_of_works, :man_power_details, :man_powers, :products, :estimate_sales, :unit_of_measurements
   resources :varieties
   #resources :income_statements

   post 'estimate_sales/verify_new_estimate_sale'
   post 'estimate_sales/type_of_crop'
   post 'supplies/calculate_subtotal'
   post 'cost_oper_machine_conts/get_farming_plot'
   get  'income_statements/index'
   get "income_statements" => "income_statements#index"
   post 'income_statements/get_income_statement'
  
   devise_for :users

   resources :program_productions do
    resources :estimate_sales #-> url.com/logs/:log_id/meals/:id
   end

   resources :cost_oper_machines do
    resources :cost_oper_machine_details
   end

   resources :cost_oper_machine_conts do
    resources :cost_oper_machine_cont_details
   end

   resources :supplies do
    resources :supply_details
   end

   resources :man_powers do
    resources :man_power_details
   end

   resources :manu_indi_expenses do
    resources :manu_indi_expense_dets
   end

   resources :supplies do
    resources :supply_details
   end
   
   resources :mark_spendings do
    resources :mark_spending_dets
   end
end

app/models/cost_oper_machine_cont.rb
class CostOperMachineCont < ApplicationRecord 
	
	belongs_to :program_production

	has_many :cost_oper_machine_cont_details, inverse_of: :cost_oper_machine_cont, :dependent => :destroy
	accepts_nested_attributes_for :cost_oper_machine_cont_details
	validates_presence_of :program_production_id, :total
  
	

	 def self.get_list_cost_outsourced()
		
		CostOperMachineCont.find_by_sql "   
														SELECT * FROM 
														(
															SELECT
																cost_oper_machine_conts.id AS machine_cont_id
																,RIGHT(CONCAT('000',cost_oper_machine_conts.id::text),3)  AS code
																,farming_plots.name AS farm_plots
																,program_production 
																,unit_of_measurements.name AS um
																,type_of_services.name AS type_service
																,cost_oper_machine_conts.total
															FROM 
																cost_oper_machine_conts
																,cost_oper_machine_cont_details
																,farming_plots
																,program_productions AS prog_prodt
																,estimate_sales
																,unit_of_measurements
																,type_of_services
															WHERE 
																cost_oper_machine_cont_details.type_of_service_id = type_of_services.id
															AND 
																estimate_sales.farming_plot_id = farming_plots.id
															AND 
																prog_prodt.estimate_sale_id =  estimate_sales.id
															AND 
																type_of_services.unit_of_measurement_id = unit_of_measurements.id
														) AS algo                     
										"
										
	 end
	 def self.get_farming_plot()
		
			CostOperMachineCont.find_by_sql
								"
									SELECT * FROM 
									(
										SELECT
											farming_plots.name AS parcela
											 ,program_production
										FROM 
											farming_plots
											 ,program_productions
											 ,estimate_sales
										WHERE 
											 estimate_sales.farming_plot_id = farming_plots.id
														AND program_productions.estimate_sale_id =  estimate_sales.id
													GROUP BY 
														farming_plots.name
														 ,program_production
											  ) AS consulta
								"
								
	 end
end

app/controllers/cost_oper_machine_conts_controller.rb
class CostOperMachineContsController < ApplicationController
	#
	# Costo operativo de maquinaria tercerizada
	#
	before_action :authenticate_user!
	before_action :set_cost_oper_machine_cont, only: [:show, :edit, :update, :destroy]  

	# GET /cost_oper_machine_conts
	# GET /cost_oper_machine_conts.json
	def index
		get_all 
		@cost_oper_machine_conts = CostOperMachineCont.all
		#@cost_oper_machine_conts = CostOperMachineCont.get_list_cost_outsourced
	end
	# GET /cost_oper_machine_conts/1
	# GET /cost_oper_machine_conts/1.json
	def show
	end

	# GET /cost_oper_machine_conts/new
	def new
		get_all
		@cost_oper_machine_cont = CostOperMachineCont.new
		program_production                 = ProgramProduction.last()
		unless program_production.nil?

			@quantity_production    = program_production.program_production
			@program_production_id  = program_production.id
			sale                    = EstimateSale.find(program_production.estimate_sale_id)
			farm                    = FarmingPlot.find(sale.farming_plot_id)
			@farm_name              = farm.name
			@farm_area              = farm.area
		end
	end

	# GET /cost_oper_machine_conts/1/edit
	def edit
		get_all
		cost_oper_machine_cont_master            = CostOperMachineCont.find(params[:id])
		@cost_oper_machine_cont_details          = CostOperMachineContDetail.where(cost_oper_machine_cont_id: cost_oper_machine_cont_master.id)
		@program_production_id                   = cost_oper_machine_cont_master.program_production_id
		@farm_name                               = cost_oper_machine_cont_master.program_production.estimate_sale.farming_plot.name
		@farm_area                               = cost_oper_machine_cont_master.program_production.estimate_sale.farming_plot.area
		@quantity_production                     = cost_oper_machine_cont_master.program_production.program_production
		@total                                   = @cost_oper_machine_cont_details.sum(:subtotal)
	end

	# POST /cost_oper_machine_conts
	# POST /cost_oper_machine_conts.json
	def create
		get_all
		@cost_oper_machine_cont = CostOperMachineCont.new(cost_oper_machine_cont_params)
		
		if @cost_oper_machine_cont.save
			render json: { contenido: @cost_oper_machine_cont, location: cost_oper_machine_cont_url(@cost_oper_machine_cont),result: :ok },status: 200
		else
			render json:  @cost_oper_machine_cont.errors, status: :unprocessable_entity 
		end
	end

  # PATCH/PUT /cost_oper_machine_conts/1
  # PATCH/PUT /cost_oper_machine_conts/1.json
  def update
  	get_all
  	respond_to do |format|
  		if @cost_oper_machine_cont.update(cost_oper_machine_cont_params)
			  #format.html { redirect_to @cost_oper_machine_cont, notice: 'Cost oper machine cont was successfully updated.' }
			  format.json { render :show, status: :ok, location: @cost_oper_machine_cont }
			else
			  #format.html { render :edit }
			  format.json { render json: @cost_oper_machine_cont.errors, status: :unprocessable_entity }
			end
		end
	end

  # DELETE /cost_oper_machine_conts/1
  # DELETE /cost_oper_machine_conts/1.json
  def destroy
  	@cost_oper_machine_cont.destroy
  	respond_to do |format|
  		format.html { redirect_to cost_oper_machine_conts_url, notice: 'Cost oper machine cont was successfully destroyed.' }
  		format.json { head :no_content }
  	end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_cost_oper_machine_cont
  	@cost_oper_machine_cont = CostOperMachineCont.find(params[:id])
		# @traerPrograma = CostOperMachineCont.find(params[:idPrograma])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def cost_oper_machine_cont_params
		params.require(:cost_oper_machine_cont).permit(:program_production_id, :total, cost_oper_machine_cont_details_attributes: [:type_of_service_id,:amount, :subtotal])
	end

	def get_all
		# @programs = CostOperMachineCont.program_production.collect {|p| [ p.program_production, p.id ] }
		@type_services = TypeOfService.all.collect {|p| [ p.name, p.id ,{"data-price"=> p.price, "data-u_measure"=>p.unit_of_measurement.name}] } 
		@unit_measure = { HECTAREA: 1, HORAS: 0 }
		@path = " / crear estimación / costo operativo de máquinas tercerizadas"
	  	@edit_name = "Editar costo operativo de máquina tercerizada"
	end
end

app/helpers/cost_oper_machine_conts_helper.rb
module CostOperMachineContsHelper
end

app/views/cost_oper_machine_conts/edit.html.erb
<%= render 'form', cost_oper_machine_cont: @cost_oper_machine_cont %>

app/views/cost_oper_machine_conts/index.html.erb
<div class="table-responsive">
   <table data-width="100%"  
      data-flat="true"
      data-response-handler="flatJSON"
      data-search="true"                
      class="table table-hover table-striped table-condensed display" 
      data-toggle="table"
      data-show-toggle="true"                
      data-show-refresh="false" 
      data-pagination="true" 
      onlyInfoPagination="false" 
      data-icons="icons" data-sort-name="program_production_id" data-sort-order="desc" 
      data-card-view="false"
   >
		<thead>
			<tr>
				<th data-width='20' data-field="id" data-checkbox="false">#</th>
				<th data-width='20'data-field="code" data-sortable="true">Cod</th> 
				<th data-field="program_production_id" data-sortable="true">Parcela</th> 
				<th data-field="type_of_crop_id" data-sortable="true">Tipo de cultivo</th> 
				<th data-align="right" data-field="total">Total</th>
				<th data-width='80' data-formatter="actionFormatter" data-align="right" data-events="actionEvents">Acción</th>
			</tr>
		</thead>
		<tbody>
			<% @cost_oper_machine_conts.each do |machine_cont| %>
			<tr>
				<td><%= machine_cont.id %></td>
				<td><%= machine_cont.id %></td>
				<td><%= machine_cont.program_production.estimate_sale.farming_plot.name %></td>
				<td><%= machine_cont.program_production.estimate_sale.type_of_crop.name %></td>
				<td><%= number_with_precision(machine_cont.total, :precision => 0, :delimiter => '.' ) %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>
<input type="hidden" id="controller" value="<%= controller_name%>">

app/views/cost_oper_machine_conts/new.html.erb
</br>
<%= render 'form', cost_oper_machine_cont: @cost_oper_machine_cont %>

app/views/cost_oper_machine_conts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Farming plot:</strong>
  <%= @cost_oper_machine_cont.farming_plot_id %>
</p>

<p>
  <strong>Total:</strong>
  <%= @cost_oper_machine_cont.total %>
</p>

<%= link_to 'Edit', edit_cost_oper_machine_cont_path(@cost_oper_machine_cont) %> |
<%= link_to 'Back', cost_oper_machine_conts_path %>

app/views/cost_oper_machine_conts/traer_programaProduccion.html.erb
<p>sou a vista do controller custo operativo </p>
@