config/routes.rb
Rails.application.routes.draw do
  

  resources :depreciation_details
  resources :depreciations
  resources :revaluation_coefficients
   resources :man_power_details
   resources :cost_oper_machines
   resources :type_machines
   root to: "home#index"
   #match 'history_sales' => 'type_of_crops/history_sales', :via => :post


   resources :history_sales,:type_of_crops, :program_productions, :people , :farming_plots, :manu_indi_expense_dets, :manu_indi_expenses, :stru_expense_dets
   resources :structure_expenses, :mark_spending_dets, :mark_spendings, :supply_details, :supplies, :chart_of_accounts, :cost_oper_machine_conts
   resources :cost_oper_machine_cont_details, :type_of_services, :fuels,:cost_oper_machine_details,:cost_oper_machines, :implements
   resources :machines, :models, :brands, :type_of_works, :man_power_details, :man_powers, :products, :estimate_sales, :unit_of_measurements
   resources :varieties
   #resources :income_statements

   post 'estimate_sales/verify_new_estimate_sale'
   post 'estimate_sales/type_of_crop'
   post 'supplies/calculate_subtotal'
   post 'cost_oper_machine_conts/get_farming_plot'
   get  'income_statements/index'
   get "income_statements" => "income_statements#index"
   post 'income_statements/get_income_statement'
  
   devise_for :users

   resources :program_productions do
    resources :estimate_sales #-> url.com/logs/:log_id/meals/:id
   end

   resources :cost_oper_machines do
    resources :cost_oper_machine_details
   end

   resources :cost_oper_machine_conts do
    resources :cost_oper_machine_cont_details
   end

   resources :supplies do
    resources :supply_details
   end

   resources :man_powers do
    resources :man_power_details
   end

   resources :manu_indi_expenses do
    resources :manu_indi_expense_dets
   end

   resources :supplies do
    resources :supply_details
   end
   
   resources :mark_spendings do
    resources :mark_spending_dets
   end
end

app/controllers/manu_indi_expenses_controller.rb
class ManuIndiExpensesController < ApplicationController

   before_action :authenticate_user!
   before_action :set_manu_indi_expense, only: [:show, :edit, :update, :destroy]

   # GET /manu_indi_expenses
   # GET /manu_indi_expenses.json
   def index
      get_all
      @manu_indi_expenses = ManuIndiExpense.all
   end

   # GET /manu_indi_expenses/1
   # GET /manu_indi_expenses/1.json
   def show
   end

   # GET /manu_indi_expenses/new
   def new
      get_all
      @manu_indi_expense      = ManuIndiExpense.new
      program                 = ProgramProduction.last()
      unless program.nil?
        @program_production_id  = program.id
      end
   end

   # GET /manu_indi_expenses/1/edit
   def edit
      get_all

      program                             = ProgramProduction.last()
      @program_production_id              = program.id

      @manu                               = ManuIndiExpense.find(params[:id])
      @manu_details                       = ManuIndiExpenseDet.where(manu_indi_expense_id: @manu.id)
      @total_fixed_and_variable           = @manu.totalFixedAndVariable
      @total_fixed                        = @manu.total_fixed
      @total_variable                     = @manu.total_variable
      

      return :json => {:contenido => @manu_details,:result => "edit"}

   end

   # POST /manu_indi_expenses
   # POST /manu_indi_expenses.json
   def create
      get_all      
      @manu_indi_expense = ManuIndiExpense.new(manu_indi_expense_params)
      puts manu_indi_expense_params
      if @manu_indi_expense.save
         render json: { contenido: @manu_indi_expense, location: manu_indi_expense_url(@manu_indi_expense),result: :ok },status: 200
      else
         render json:  @manu_indi_expense.errors, status: :unprocessable_entity 
      end
   end

   # PATCH/PUT /manu_indi_expenses/1
   # PATCH/PUT /manu_indi_expenses/1.json
   def update
      respond_to do |format|
         if @manu_indi_expense.update(manu_indi_expense_params)
            format.html { redirect_to @manu_indi_expense, notice: 'Manu indi expense was successfully updated.' }
            format.json { render :index, status: :ok, location: @manu_indi_expense }
         else
            format.html { render :edit }
            format.json { render json: @manu_indi_expense.errors, status: :unprocessable_entity }
         end
      end
   end

   # DELETE /manu_indi_expenses/1
   # DELETE /manu_indi_expenses/1.json
   def destroy
      @manu_indi_expense.destroy
      respond_to do |format|
         format.html { redirect_to manu_indi_expenses_url, notice: 'Manu indi expense was successfully destroyed.' }
         format.json { head :no_content }
      end
   end

   private
   # Use callbacks to share common setup or constraints between actions.
   def set_manu_indi_expense
      @manu_indi_expense = ManuIndiExpense.find(params[:id])
   end

   # Never trust parameters from the scary internet, only allow the white list through.
   def manu_indi_expense_params                                                                                                                 
      params.require(:manu_indi_expense).permit(:program_production_id, :chart_of_account_id, :total_fixed, :total_variable, :totalFixedAndVariable,{ manu_indi_expense_dets_attributes: [:name, :isFixed, :subtotal]})
   end
   def get_all
      @path             = " / crear estimación / gastos indirectos de producción"
      @edit_name        = "Editar gastos indirectos de produccción"
      @select_list      = { FIJO: 1, VARIABLE: 0 }
      @edit_name        = "Editar gastos indirectos de producción"
   end
end

app/helpers/manu_indi_expenses_helper.rb
module ManuIndiExpensesHelper
end

app/views/manu_indi_expenses/_form.html.erb
<%= form_for( @manu_indi_expense, html: { id: 'form_manu_indi_expenses', remote:true,"data-type": "json",'data-model' => 'manu_indi_expense'}) do |f| %>

      <div class="col-sm-6 col-lg-12 col-md-12 col-xs-12">
            <div class="row">
               <div class="col-md-4">
                  <div class="form-group">
                     <%= f.label :program_production_id,"Descripción del gasto :" ,class: " col-sm-6 col-lg-10 col-xs-12"%>
                        <input type="text" name="manu_indi[descr_expense]" id="manu_indi_descr_expense" class="form-control" required/>
                  </div>
               </div>
               <div class="col-md-3">
                  <div class="form-group">
                     <%= f.label :program_production_id,"Tipo de gasto:" ,class: "col-sm-6 col-lg-8 col-xs-12" %>
                    <%= select("manu_indi", "type_expense", options_for_select([['FIJO', 1], ['VARIABLE', 0]]),{}, {class: "form-control",required: true})%>

                  </div>
               </div>
               <div class="col-md-3">
                  <div class="form-group">
                     <%= f.label :program_production_id,"Monto del gasto :" ,class: "col-sm-6 col-lg-10 col-xs-12"%>
                     <input type="text" name="manu_indi[subtotal]" id="manu_indi_subtotal"  class="form-control text-right only_numbers" required/>
                  </div>
               </div>
                  <btn><a class="btn btn-default btn-sm align_btn" id="btn_add_manu_indi_expense">Agregar</a></btn>
            </div>

            <table 
            id="tb_manu_indi_expense"
            data-width="100%"  
            data-search="false"                
            class="table table-hover table-striped table-condensed display" 
            data-toggle="table"
            data-show-toggle="false"                
            data-show-refresh="false" 
            data-pagination="true" 
            onlyInfoPagination="false" 
            data-icons="icons" data-sort-name="code" data-sort-order="asc" 
            data-card-view="false"
            data-checkbox-header="false"
            >
               <thead>
                  <tr>
                     <th data-field="id" data-checkbox="true" data-checkbox-header="false"></th>
                     <th data-field="code">Cod.</th>
                     <th data-field="descr_expense">Descripción del gasto</th>
                     <th data-field="descr_expense_id" class="hide"></th>
                     <th data-field="type_expense">Tipo del gasto</th>
                     <th data-field="type_expense_id" class="hide"></th>
                     <th data-field="subtotal" data-halign='right'>Monto</th>
                     <th data-field="subtotal_id" class="hide"></th>
                     <th data-width="60" data-halign='center' data-field="Action" data-events="remove">Acción</th>
                  </tr>
               </thead>
               <tbody>
                  <% if (controller.action_name == "edit") %>
                        <% @manu_details.each do |manu_indi_expense_dets| %>
                        <tr>
                           <td style="display:none"><%= manu_indi_expense_dets.id%></td>
                           <td ><%= manu_indi_expense_dets.id%></td>
                           <td ><%= manu_indi_expense_dets.name %></td>
                           <td style="display:none"><!--vacio al crear nuevo --></td>
                           <td><%= manu_indi_expense_dets.isFixed ? "FIJO" : "VARIABLE"%></td>
                           <td style="display:none"><!--vacio al crear nuevo --></td>
                           <td><%= number_with_precision( manu_indi_expense_dets.subtotal, :precision => 0, :delimiter => '.' ) %></td>                  
                           <td style="display:none"></td>
                           <td>
                              <a class="change_status btn btn-danger btn-sm" href="" title="Cambiar status" >
                                 <i class="fa fa-minus-square"></i>
                              </a>
                           </td>
                        </tr>
                     <% end %>   
                  <div class="hide">
                     <%= f.text_field :total_fixed, :value => @total_fixed ,:id => "total_fixed" %>
                     <%= f.text_field :total_variable, :value => @total_variable,:id => "total_variable"%>
                     <%= f.text_field :totalFixedAndVariable, :value => @total_fixed_and_variable, :id => "total"%>
                  </div>
                  <% else %>
                  <div class="hide">
                     <%= f.text_field :totalFixedAndVariable, :value => 0 ,:id => "total" %>
                     <%= f.text_field :total_fixed, :value => 0 ,:id => "total_fixed" %>
                     <%= f.text_field :total_variable, :value => 0 ,:id => "total_variable" %>
                  </div>
               <% end %>
               </tbody>                    
               <tfoot>
                  <tr>
                     <td class="h6 font-weight-bold" colspan="4"><strong>TOTAL FIJO :<strong></td>
                     <td colspan="9" class="font-weight-bold text-right">
                     <strong><span class="total_fixed"> <%= @total_fixed %></span><strong>
                     </td>
                  </tr>
                 <tr>
                     <td class="h6 font-weight-bold" colspan="4"><strong>TOTAL VARIABLE :<strong></td>
                     <td colspan="9" class="font-weight-bold text-right">
                        <strong>
                           <span class="total_variable">
                              <%=number_with_precision( @total_variable, :precision => 0, :delimiter => '.' ) %></span><strong>
                           </span>
                        <strong>
                     </td>
                 </tr>
                <tr>
                  <td class="h6 font-weight-bold" colspan="4"><strong>TOTAL FIJO & VARIABLE :<strong></td>
                  <td colspan="9" class="font-weight-bold text-right">
                     <strong>
                        <span class="total">
                           <%=number_with_precision( @total_fixed_and_variable, :precision => 0, :delimiter => '.' ) %></span><strong>
                        </span>
                     <strong>
                  </td>
                 </tr>
               </tfoot>
               <div id="add_row_cost_oper_cont"></div>
            </table>
         <%= f.hidden_field :program_production_id, :value => @program_production_id %>
      </div>

   <% end %>
<input type="hidden" id="controller" value="<%=controller_name%>">

app/views/manu_indi_expenses/edit.html.erb
<%= render 'form', manu_indi_expense: @manu_indi_expense %>

app/views/manu_indi_expenses/index.html.erb
  <div class="table-responsive">
    <table data-width="100%"  
      data-flat="true"
      data-response-handler="flatJSON"
      data-search="true"                
      class="table table-hover table-striped table-condensed display" 
      data-toggle="table"
      data-show-toggle="true"                
      data-show-refresh="false" 
      data-pagination="true" 
      onlyInfoPagination="false" 
      data-icons="icons" data-sort-name="code" data-sort-order="desc" 
      data-card-view="false"
    >
         <thead>
            <tr>
               <th data-field="id" data-checkbox="false">#</th>
               <th data-field="program_production_id">Parcela</th>
               <th data-field="type_of_crop_id">Cultivo</th>
               <th data-field="total_fixed" >Total de gastos fijos</th> 
               <th data-field="total_variable" >Total de gastos variables</th>  
               <th data-field="totalFixedAndVariable" >Total de gastos fijos y variables</th>  
               <th data-width='80' data-formatter="actionFormatter" data-align="right" data-events="actionEvents">Acción</th>
            </tr>
         </thead>
         <tbody>
            <% @manu_indi_expenses.each do |manu_indi_expense| %>
               <tr>
                  <td><%= manu_indi_expense.id %></td>
                  <td><%= manu_indi_expense.program_production.estimate_sale.farming_plot.name %></td>
                  <td><%= manu_indi_expense.program_production.estimate_sale.type_of_crop.name %></td>
                  <td><%= number_with_precision( manu_indi_expense.total_fixed, :precision => 0, :delimiter => '.' ) %></td>                  
                  <td><%= number_with_precision( manu_indi_expense.total_variable, :precision => 0, :delimiter => '.' ) %></td>                  
                  <td><%= number_with_precision( manu_indi_expense.totalFixedAndVariable, :precision => 0, :delimiter => '.' ) %></td>                  
               </tr>
            <% end %>
         </tbody>
      </table>
   </div>
<input type="hidden" id="controller" value="<%= controller_name%>">

app/views/manu_indi_expenses/new.html.erb
<%= render 'form', manu_indi_expense: @manu_indi_expense %>

<%= link_to 'Back', manu_indi_expenses_path %>
<%= link_to 'Anterior', new_man_power_path %>

app/views/manu_indi_expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Program production:</strong>
  <%= @manu_indi_expense.program_production_id %>
</p>

<p>

<p>
  <strong>Total fixed:</strong>
  <%= @manu_indi_expense.total_fixed %>
</p>

<p>
  <strong>Total variable:</strong>
  <%= @manu_indi_expense.total_variable %>
</p>

<p>
  <strong>Totalfixedandvariable:</strong>
  <%= @manu_indi_expense.totalFixedAndVariable %>
</p>

<%= link_to 'Edit', edit_manu_indi_expense_path(@manu_indi_expense) %> |
<%= link_to 'Back', manu_indi_expenses_path %>