config/routes.rb
Rails.application.routes.draw do
  

  resources :depreciation_details
  resources :depreciations
  resources :revaluation_coefficients
   resources :man_power_details
   resources :cost_oper_machines
   resources :type_machines
   root to: "home#index"
   #match 'history_sales' => 'type_of_crops/history_sales', :via => :post


   resources :history_sales,:type_of_crops, :program_productions, :people , :farming_plots, :manu_indi_expense_dets, :manu_indi_expenses, :stru_expense_dets
   resources :structure_expenses, :mark_spending_dets, :mark_spendings, :supply_details, :supplies, :chart_of_accounts, :cost_oper_machine_conts
   resources :cost_oper_machine_cont_details, :type_of_services, :fuels,:cost_oper_machine_details,:cost_oper_machines, :implements
   resources :machines, :models, :brands, :type_of_works, :man_power_details, :man_powers, :products, :estimate_sales, :unit_of_measurements
   resources :varieties
   #resources :income_statements

   post 'estimate_sales/verify_new_estimate_sale'
   post 'estimate_sales/type_of_crop'
   post 'supplies/calculate_subtotal'
   post 'cost_oper_machine_conts/get_farming_plot'
   get  'income_statements/index'
   get "income_statements" => "income_statements#index"
   post 'income_statements/get_income_statement'
  
   devise_for :users

   resources :program_productions do
    resources :estimate_sales #-> url.com/logs/:log_id/meals/:id
   end

   resources :cost_oper_machines do
    resources :cost_oper_machine_details
   end

   resources :cost_oper_machine_conts do
    resources :cost_oper_machine_cont_details
   end

   resources :supplies do
    resources :supply_details
   end

   resources :man_powers do
    resources :man_power_details
   end

   resources :manu_indi_expenses do
    resources :manu_indi_expense_dets
   end

   resources :supplies do
    resources :supply_details
   end
   
   resources :mark_spendings do
    resources :mark_spending_dets
   end
end

app/models/depreciation.rb
class Depreciation < ApplicationRecord
   belongs_to :program_production
   belongs_to :cost_oper_machine
   has_many :depreciation_details, inverse_of: :depreciation, :dependent => :destroy
   accepts_nested_attributes_for :depreciation_details

   validates_presence_of :cost_oper_machine_id, :total

end

app/controllers/depreciations_controller.rb
class DepreciationsController < ApplicationController
  before_action :set_depreciation, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @depreciations = Depreciation.all
    respond_with(@depreciations)
  end

  def show
    respond_with(@depreciation)
  end

  def new
    @depreciation = Depreciation.new
    respond_with(@depreciation)
  end

  def edit
  end

  def create
    @depreciation = Depreciation.new(depreciation_params)
    @depreciation.save
    respond_with(@depreciation)
  end

  def update
    @depreciation.update(depreciation_params)
    respond_with(@depreciation)
  end

  def destroy
    @depreciation.destroy
    respond_with(@depreciation)
  end

  private
    def set_depreciation
      @depreciation = Depreciation.find(params[:id])
    end

    def depreciation_params
      params.require(:depreciation).permit(:program_production_id, :cost_oper_machine_id, :total)
    end
end

app/helpers/depreciations_helper.rb
module DepreciationsHelper
end

app/views/depreciations/_form.html.erb
<%= form_for(depreciation) do |f| %>
  <% if depreciation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(depreciation.errors.count, "error") %> prohibited this depreciation from being saved:</h2>

      <ul>
      <% depreciation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :program_production_id %>
    <%= f.text_field :program_production_id %>
  </div>

  <div class="field">
    <%= f.label :cost_oper_machine_id %>
    <%= f.text_field :cost_oper_machine_id %>
  </div>

  <div class="field">
    <%= f.label :total %>
    <%= f.text_field :total %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/depreciations/edit.html.erb
<h1>Editing Depreciation</h1>

<%= render 'form', depreciation: @depreciation %>

<%= link_to 'Show', @depreciation %> |
<%= link_to 'Back', depreciations_path %>

app/views/depreciations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Depreciations</h1>

<table>
  <thead>
    <tr>
      <th>Program production</th>
      <th>Cost oper machine</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @depreciations.each do |depreciation| %>
      <tr>
        <td><%= depreciation.program_production %></td>
        <td><%= depreciation.cost_oper_machine %></td>
        <td><%= depreciation.total %></td>
        <td><%= link_to 'Show', depreciation %></td>
        <td><%= link_to 'Edit', edit_depreciation_path(depreciation) %></td>
        <td><%= link_to 'Destroy', depreciation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Depreciation', new_depreciation_path %>

app/views/depreciations/new.html.erb
<h1>New Depreciation</h1>

<%= render 'form', depreciation: @depreciation %>

<%= link_to 'Back', depreciations_path %>

app/views/depreciations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Program production:</strong>
  <%= @depreciation.program_production %>
</p>

<p>
  <strong>Cost oper machine:</strong>
  <%= @depreciation.cost_oper_machine %>
</p>

<p>
  <strong>Total:</strong>
  <%= @depreciation.total %>
</p>

<%= link_to 'Edit', edit_depreciation_path(@depreciation) %> |
<%= link_to 'Back', depreciations_path %>