config/routes.rb
Rails.application.routes.draw do
  

  resources :depreciation_details
  resources :depreciations
  resources :revaluation_coefficients
   resources :man_power_details
   resources :cost_oper_machines
   resources :type_machines
   root to: "home#index"
   #match 'history_sales' => 'type_of_crops/history_sales', :via => :post


   resources :history_sales,:type_of_crops, :program_productions, :people , :farming_plots, :manu_indi_expense_dets, :manu_indi_expenses, :stru_expense_dets
   resources :structure_expenses, :mark_spending_dets, :mark_spendings, :supply_details, :supplies, :chart_of_accounts, :cost_oper_machine_conts
   resources :cost_oper_machine_cont_details, :type_of_services, :fuels,:cost_oper_machine_details,:cost_oper_machines, :implements
   resources :machines, :models, :brands, :type_of_works, :man_power_details, :man_powers, :products, :estimate_sales, :unit_of_measurements
   resources :varieties
   #resources :income_statements

   post 'estimate_sales/verify_new_estimate_sale'
   post 'estimate_sales/type_of_crop'
   post 'supplies/calculate_subtotal'
   post 'cost_oper_machine_conts/get_farming_plot'
   get  'income_statements/index'
   get "income_statements" => "income_statements#index"
   post 'income_statements/get_income_statement'
  
   devise_for :users

   resources :program_productions do
    resources :estimate_sales #-> url.com/logs/:log_id/meals/:id
   end

   resources :cost_oper_machines do
    resources :cost_oper_machine_details
   end

   resources :cost_oper_machine_conts do
    resources :cost_oper_machine_cont_details
   end

   resources :supplies do
    resources :supply_details
   end

   resources :man_powers do
    resources :man_power_details
   end

   resources :manu_indi_expenses do
    resources :manu_indi_expense_dets
   end

   resources :supplies do
    resources :supply_details
   end
   
   resources :mark_spendings do
    resources :mark_spending_dets
   end
end

app/models/manu_indi_expense_det.rb
class ManuIndiExpenseDet < ApplicationRecord
	belongs_to :manu_indi_expense, inverse_of: :manu_indi_expense_dets
  	validates_presence_of :manu_indi_expense,:name,:isFixed,:subtotal

end

app/controllers/manu_indi_expense_dets_controller.rb
class ManuIndiExpenseDetsController < ApplicationController
  before_action :set_manu_indi_expense_det, only: [:show, :edit, :update, :destroy]

  # GET /manu_indi_expense_dets
  # GET /manu_indi_expense_dets.json
  def index
    @manu_indi_expense_dets = ManuIndiExpenseDet.all
  end

  # GET /manu_indi_expense_dets/1
  # GET /manu_indi_expense_dets/1.json
  def show
  end

  # GET /manu_indi_expense_dets/new
  def new
    @manu_indi_expense_det = ManuIndiExpenseDet.new
  end

  # GET /manu_indi_expense_dets/1/edit
  def edit
  end

  # POST /manu_indi_expense_dets
  # POST /manu_indi_expense_dets.json
   def create
    @manu_indi_expense_det = ManuIndiExpenseDet.new(manu_indi_expense_det_params)

      respond_to do |format|
         if @manu_indi_expense_det.save
           format.html { redirect_to @manu_indi_expense_det, notice: 'Manu indi expense det was successfully created.' }
           format.json { render :show, status: :created, location: @manu_indi_expense_det }
         else
           format.html { render :new }
           format.json { render json: @manu_indi_expense_det.errors, status: :unprocessable_entity }
         end
      end
   end

  # PATCH/PUT /manu_indi_expense_dets/1
  # PATCH/PUT /manu_indi_expense_dets/1.json
   def update
      respond_to do |format|
         if @manu_indi_expense_det.update(manu_indi_expense_det_params)
           format.html { redirect_to @manu_indi_expense_det, notice: 'Manu indi expense det was successfully updated.' }
           format.json { render :show, status: :ok, location: @manu_indi_expense_det }
         else
           format.html { render :edit }
           format.json { render json: @manu_indi_expense_det.errors, status: :unprocessable_entity }
         end
      end
   end

  # DELETE /manu_indi_expense_dets/1
  # DELETE /manu_indi_expense_dets/1.json
   def destroy
      @manu_indi_expense_det.destroy
      respond_to do |format|
         format.html { redirect_to manu_indi_expense_dets_url, notice: 'Manu indi expense det was successfully destroyed.' }
         format.json { head :no_content }
      end
   end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manu_indi_expense_det
      @manu_indi_expense_det = ManuIndiExpenseDet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manu_indi_expense_det_params
      params.require(:manu_indi_expense_det).permit(:manu_indi_expense_id, :name, :isFixed, :subtotal)
    end
end

app/helpers/manu_indi_expense_dets_helper.rb
module ManuIndiExpenseDetsHelper
end

app/views/manu_indi_expense_dets/_form.html.erb
<%= form_for(manu_indi_expense_det) do |f| %>
  <% if manu_indi_expense_det.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(manu_indi_expense_det.errors.count, "error") %> prohibited this manu_indi_expense_det from being saved:</h2>

      <ul>
      <% manu_indi_expense_det.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :manu_indi_expense_id %>
    <%= f.text_field :manu_indi_expense_id %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :isFixed %>
    <%= f.check_box :isFixed %>
  </div>

  <div class="field">
    <%= f.label :subtotal %>
    <%= f.text_field :subtotal %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/manu_indi_expense_dets/edit.html.erb
<h1>Editing Manu Indi Expense Det</h1>

<%= render 'form', manu_indi_expense_det: @manu_indi_expense_det %>

<%= link_to 'Show', @manu_indi_expense_det %> |
<%= link_to 'Back', manu_indi_expense_dets_path %>

app/views/manu_indi_expense_dets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Manu Indi Expense Dets</h1>

<table>
  <thead>
    <tr>
      <th>Manu indi expense</th>
      <th>Name</th>
      <th>Isfixed</th>
      <th>Subtotal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @manu_indi_expense_dets.each do |manu_indi_expense_det| %>
      <tr>
        <td><%= manu_indi_expense_det.manu_indi_expense %></td>
        <td><%= manu_indi_expense_det.name %></td>
        <td><%= manu_indi_expense_det.isFixed %></td>
        <td><%= manu_indi_expense_det.subtotal %></td>
        <td><%= link_to 'Show', manu_indi_expense_det %></td>
        <td><%= link_to 'Edit', edit_manu_indi_expense_det_path(manu_indi_expense_det) %></td>
        <td><%= link_to 'Destroy', manu_indi_expense_det, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Manu Indi Expense Det', new_manu_indi_expense_det_path %>

app/views/manu_indi_expense_dets/new.html.erb
<h1>New Manu Indi Expense Det</h1>

<%= render 'form', manu_indi_expense_det: @manu_indi_expense_det %>

<%= link_to 'Back', manu_indi_expense_dets_path %>

app/views/manu_indi_expense_dets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Manu indi expense:</strong>
  <%= @manu_indi_expense_det.manu_indi_expense %>
</p>

<p>
  <strong>Name:</strong>
  <%= @manu_indi_expense_det.name %>
</p>

<p>
  <strong>Isfixed:</strong>
  <%= @manu_indi_expense_det.isFixed %>
</p>

<p>
  <strong>Subtotal:</strong>
  <%= @manu_indi_expense_det.subtotal %>
</p>

<%= link_to 'Edit', edit_manu_indi_expense_det_path(@manu_indi_expense_det) %> |
<%= link_to 'Back', manu_indi_expense_dets_path %>